<?php

namespace SultanovPackage\MicroCommands;

use SultanovPackage\MicroCommands\Console\ConsoleMicroCommand;
use SultanovSolutions\LaravelBase\Providers\BaseServiceProvider;
use SultanovPackage\MicroCommands\Console\ModelMicroCommand;

class ServiceProvider extends BaseServiceProvider
{
    protected array $commands = [
        ConsoleMicroCommand::class,
        ModelMicroCommand::class,
    ];

    public function onBoot(): void
    {
        parent::onBoot(); // TODO: Change the autogenerated stub

        $this->commands($this->commands);
    }
}
