<?php

namespace SultanovPackage\MicroCommands;

use SultanovPackage\MicroCommands\Console\Commands\FactoryMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\ConsoleMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\MigrateMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\ModelMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\SeederMicroCommand;
use SultanovSolutions\LaravelBase\Providers\BaseServiceProvider;

class ServiceProvider extends BaseServiceProvider
{
    protected array $commands = [
        ConsoleMicroCommand::class,
        ModelMicroCommand::class,
        FactoryMicroCommand::class,
        MigrateMicroCommand::class,
        SeederMicroCommand::class,
    ];

    public function onBoot(): void
    {
        parent::onBoot(); // TODO: Change the autogenerated stub

        $this->commands($this->commands);
    }
}
