<?php

namespace SultanovPackage\MicroCommands;

use SultanovPackage\MicroCommands\Console\Commands\CastMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\ConsoleMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\ControllerMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\EventMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\ExceptionMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\FactoryMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\ListenerMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\ModelMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\RequestMicroCommand;
use SultanovPackage\MicroCommands\Console\Commands\SeederMicroCommand;
use SultanovSolutions\LaravelBase\Providers\BaseServiceProvider;

class ServiceProvider extends BaseServiceProvider
{
    protected array $commands = [
        ConsoleMicroCommand::class,
        ModelMicroCommand::class,
        FactoryMicroCommand::class,
        SeederMicroCommand::class,
        ControllerMicroCommand::class,
        RequestMicroCommand::class,
//        PolicyMicroCommand::class,
        EventMicroCommand::class,
        ListenerMicroCommand::class,
        ExceptionMicroCommand::class,
        CastMicroCommand::class,
    ];

    public function onBoot(): void
    {
        parent::onBoot(); // TODO: Change the autogenerated stub

        $this->commands($this->commands);
    }
}
